### ISSUE TITLE
Enable using coverageSelection_*.json for measurements

### ISSUE THREAD

**Issue by stro18** [DaGeRe/peass#48]
Currently, it is not possible to use coverageSelection_*.json for measurements because it does not contain the first version. 

The following exception occured when passing the file with `-executionfile results/coverageSelection_tomcat.json`. The version 6cf20b4a83f1e5b2ae86525b6b96389e801776b2 (mentioned in the error), was the first version

java.lang.RuntimeException: Did not find 6cf20b4a83f1e5b2ae86525b6b96389e801776b2 in given PRONTO-files!
        at de.dagere.peass.DependencyTestStarter.getStartVersionIndex(DependencyTestStarter.java:122)
        at de.dagere.peass.DependencyTestStarter.call(DependencyTestStarter.java:74)
        at de.dagere.peass.DependencyTestStarter.call(DependencyTestStarter.java:38)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at de.dagere.peass.PeASSMain.main(PeASSMain.java:30)

**Comment by stro18** [comment]
Thanks, this works now.
