### ISSUE TITLE
Fix execution of parameterized tests

### ISSUE THREAD

**Issue by stro18** [DaGeRe/peass#63]
**Description**
When executing parameterized tests of Tomcat, the following Exception occurs:

No tests found matching Method doTest(org.apache.tomcat.util.http.TestHeaderUtiltoPrintableString) from [org.junit.internal.requests.ClassRequest@42eca56e](https://mail.uni-leipzig.de/portal/imp/dynamic.php?page=mailbox#)
java.lang.Exception: No tests found matching Method doTest(org.apache.tomcat.util.http.TestHeaderUtiltoPrintableString) from [org.junit.internal.requests.ClassRequest@42eca56e](https://mail.uni-leipzig.de/portal/imp/dynamic.php?page=mailbox#)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)

Note: Occurred with version 0.1.12 of Peass.

**Comment by stro18** [comment]
The described exception is not occurring anymore in version 0.2.1-SNAPSHOT of Peass.

**Comment by DaGeRe** [comment]
Thanks, than I'll close this issue.
